name: env_hicsr
channels:
    - defaults
    - pytorch
    - conda-forge
    - bioconda 
dependencies:
    - python=3.6
    - numpy=1.16.3
    - pyyaml=5.3
    - matplotlib=3.1.3
    - tensorboard=2.0.0
    - pytorch=1.4.0
    - pillow=7.0.0
    - cooler