name: env_deephic
channels:
    - defaults
    - pytorch
    - conda-forge
dependencies:
    - python=3.6.7
    - numpy=1.16.3
    - pyyaml=5.3
    - matplotlib=3.1.3
    - tensorboard=2.0.0
    - pytorch=1.4.0
    - pillow=7.0.0
    - torchvision=0.3.0
    - scipy=1.3.0
    - pandas=0.24.2
    - scikit-learn=0.21.2
    - matplotlib=3.1.0
    - tqdm=4.32.2
    - visdom=0.1.8.8