name: env_hicgan
channels:
    - defaults
    - conda-forge
    - bioconda
dependencies:
    - python=3.6
    - numpy=1.16.3
    - pyyaml=5.3
    - matplotlib=3.1.3
    - cooler
    - TensorFlow=2.0
    - pip
    - pip:
        - TensorLayer
    - hickle