name: env_gan
channels:
    - defaults
    - pytorch
    - conda-forge
    - bioconda 
dependencies:
    - python=3.6
    - numpy=1.16.3
    - pyyaml=5.3
    - matplotlib=3.1.3
    - cooler
    - TensorFlow=2.0
    - TensorLayer = 1.9.1
    - hickle = 2.1.0