name: env_hicgan
channels:
    - defaults
    - conda-forge
    - bioconda
    - anaconda
dependencies:
    - python=3.6
    - numpy=1.16.0
    - pyyaml=5.3
    - matplotlib=3.1.3
    - cooler
    - scikit-image
    - pip
    - pip:
        - TensorLayer==1.11.0
        - tensorflow-gpu==1.15
    - hickle