name: env_hicgan
channels:
    - defaults
    - conda-forge
    - bioconda
    - anaconda
    - engility 
dependencies:
    - python=3.6
    - numpy=1.16.0
    - pyyaml=5.3
    - matplotlib=3.1.3
    - cooler
    - tensorflow-gpu-base
    - pip
    - pip:
        - TensorLayer==1.11.0
    - hickle